/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aes;

import aes.Enums.*;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author wallejr
 */
public class SearchCases extends javax.swing.JFrame {

    /**
     * Creates new form searchByStatus
     */
    public SearchCases() {
        initComponents();
        initGUI();
    }
    
    private void initGUI()
    {
        setLocationRelativeTo(null);
        comboStatus.setModel(new DefaultComboBoxModel<>(Status.values()));
        comboCateg.setModel(new DefaultComboBoxModel<>(Kompetens.values()));
        
       // comboAssigne.setModel(new DefaultComboBoxModel<>(blaaha));
        Enum[] xarray = new Enum[12];
        int counter = 0;
        
        for (Enum pi : PersonalInstallation.values())
        {
            xarray[counter++] = pi;
        }
        for ( Enum pn : PersonalNetwork.values())
        {
            xarray[counter++] = pn;

        }
        for (Enum ps : PersonalSecurity.values())
        {
            xarray[counter++] = ps;
        }
                    
                   
        for (Enum pu : PersonalUsers.values())
        {
            xarray[counter++] = pu;
        }
        
         
        comboAssigne.setModel(new DefaultComboBoxModel<>(xarray));
        comboAssigne.insertItemAt("Not Assigned", 0);
        comboAssigne.setSelectedIndex(0);  
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        comboStatus = new javax.swing.JComboBox();
        btnSearchStatus = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        comboCateg = new javax.swing.JComboBox();
        btnSearcCat = new javax.swing.JButton();
        searchByID = new javax.swing.JPanel();
        txtSearcID = new javax.swing.JTextField();
        btnSearcID = new javax.swing.JButton();
        panelSearchByAssigne = new javax.swing.JPanel();
        comboAssigne = new javax.swing.JComboBox();
        btnSearcAssigne = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SEARCH WINDOW");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Search Cases");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Search by status"));

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Started" }));

        btnSearchStatus.setText("Search Case");
        btnSearchStatus.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearchStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearchStatus)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchStatus))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Search by Category"));

        comboCateg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearcCat.setText("Search Case");
        btnSearcCat.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearcCatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(comboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearcCat, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboCateg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearcCat))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        searchByID.setBorder(javax.swing.BorderFactory.createTitledBorder("Search by caseID"));

        btnSearcID.setText("Search Case");
        btnSearcID.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearcIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchByIDLayout = new javax.swing.GroupLayout(searchByID);
        searchByID.setLayout(searchByIDLayout);
        searchByIDLayout.setHorizontalGroup(
            searchByIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByIDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearcID, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearcID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        searchByIDLayout.setVerticalGroup(
            searchByIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchByIDLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(searchByIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearcID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearcID))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelSearchByAssigne.setBorder(javax.swing.BorderFactory.createTitledBorder("Search by Assigne"));
        panelSearchByAssigne.setToolTipText("");

        comboAssigne.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSearcAssigne.setText("Search Case");
        btnSearcAssigne.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSearcAssigneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSearchByAssigneLayout = new javax.swing.GroupLayout(panelSearchByAssigne);
        panelSearchByAssigne.setLayout(panelSearchByAssigneLayout);
        panelSearchByAssigneLayout.setHorizontalGroup(
            panelSearchByAssigneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchByAssigneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(comboAssigne, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                .addComponent(btnSearcAssigne, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelSearchByAssigneLayout.setVerticalGroup(
            panelSearchByAssigneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSearchByAssigneLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panelSearchByAssigneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboAssigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearcAssigne))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(searchByID, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelSearchByAssigne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSearchByAssigne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(btnCancel)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCancelActionPerformed
    {//GEN-HEADEREND:event_btnCancelActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSearchStatusActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearchStatusActionPerformed
    {//GEN-HEADEREND:event_btnSearchStatusActionPerformed
        openSearchCaseStatus();        // TODO add your handling code here:
    }//GEN-LAST:event_btnSearchStatusActionPerformed

    private void btnSearcCatActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearcCatActionPerformed
    {//GEN-HEADEREND:event_btnSearcCatActionPerformed
        openSearchCaseCat();           // TODO add your handling code here:
    }//GEN-LAST:event_btnSearcCatActionPerformed

    private void btnSearcIDActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearcIDActionPerformed
    {//GEN-HEADEREND:event_btnSearcIDActionPerformed
        openSearchCaseID();
    }//GEN-LAST:event_btnSearcIDActionPerformed

    private void btnSearcAssigneActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSearcAssigneActionPerformed
    {//GEN-HEADEREND:event_btnSearcAssigneActionPerformed
        openSearchCaseAssigne();// TODO add your handling code here:
    }//GEN-LAST:event_btnSearcAssigneActionPerformed

    private void openSearchCaseAssigne()
    {
      ShowAesLista showSearch = new ShowAesLista();
        
        
        try
        {

           showSearch.setAssigne(comboAssigne.getSelectedItem().toString());
           showSearch.listSearchAssigne();

           showSearch.setVisible(true);
           this.dispose();


        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());

        }  
    }
    
    private void openSearchCaseID()
    {
        if (validateCaseID())
        {
            ShowAesLista showSearch = new ShowAesLista();
        
        
            try
            {

               showSearch.setCaseID(Integer.parseInt(txtSearcID.getText()));
               showSearch.listSearchCaseID();

               showSearch.setVisible(true);
               this.dispose();


            } catch (Exception e)
            {
                JOptionPane.showMessageDialog(null, e.getMessage());

            }
        }
    }
    
    private boolean validateCaseID()
    {
        int tempint;
        try
        {
            tempint = Integer.parseInt(txtSearcID.getText());
            return true;
        } catch (Exception e)
        {
            return false;
        }
    }
    
    private void openSearchCaseCat()
    {
        ShowAesLista showSearch = new ShowAesLista();
        
        
        try
        {
           
           showSearch.setCaseCat(comboCateg.getSelectedItem().toString());
           showSearch.listSearchCategoryCases();
           
           showSearch.setVisible(true);
           this.dispose();
           
           
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
    }
    
    private void openSearchCaseStatus()
    {
        ShowAesLista showSearch = new ShowAesLista();
        
        
        try
        {
           
           showSearch.setCaseStatus(comboStatus.getSelectedItem().toString());
           showSearch.listSearchStatusCases();
           
           showSearch.setVisible(true);
           this.dispose();
           
           
        } catch (Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
            
        }
       
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchCases.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SearchCases().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSearcAssigne;
    private javax.swing.JButton btnSearcCat;
    private javax.swing.JButton btnSearcID;
    private javax.swing.JButton btnSearchStatus;
    private javax.swing.JComboBox comboAssigne;
    private javax.swing.JComboBox comboCateg;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panelSearchByAssigne;
    private javax.swing.JPanel searchByID;
    private javax.swing.JTextField txtSearcID;
    // End of variables declaration//GEN-END:variables
}
