package aes;


import aes.Enums.PersonalInstallation;
import aes.Enums.PersonalNetwork;
import aes.Enums.PersonalSecurity;
import aes.Enums.PersonalUsers;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author wallejr
 */
public class startForm extends javax.swing.JFrame {

    //private ListManager lsmngr = new ListManager();
   
    DefaultListModel info = new DefaultListModel();
   
    /**
     * Creates new form startForm
     */
    public startForm() 
    {
        initComponents();
        updateGUI();
        
    }
    
    private void updateGUI()
    {
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jDialog1 = new javax.swing.JDialog();
        panelCaseProperties = new javax.swing.JPanel();
        lblCaseId = new javax.swing.JLabel();
        txtCaseIdNr = new javax.swing.JTextField();
        lblCategory = new javax.swing.JLabel();
        comboCategory = new javax.swing.JComboBox();
        comboStatus = new javax.swing.JComboBox();
        lblStatus = new javax.swing.JLabel();
        lblAssignedTo = new javax.swing.JLabel();
        comboAssigned = new javax.swing.JComboBox();
        lblCreated = new javax.swing.JLabel();
        txtCreateDate = new javax.swing.JTextField();
        lblChanged = new javax.swing.JLabel();
        txtTimeChanged = new javax.swing.JTextField();
        panelRequesterInfo = new javax.swing.JPanel();
        lblUsername = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        txtUserName = new javax.swing.JTextField();
        txtFullName = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        lblDepartment = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();
        lblComputerName = new javax.swing.JLabel();
        txtComputerName = new javax.swing.JTextField();
        comboBoxCity = new javax.swing.JComboBox();
        txtFieldAvd = new javax.swing.JTextField();
        lblCreatedBy = new javax.swing.JLabel();
        txtFieldCreatedBy = new javax.swing.JTextField();
        panelCaseRequest = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        lblTitle1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        panelWorkTask = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listWorkTask = new javax.swing.JList();
        panelComments = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtComments = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        panelTimeInfo = new javax.swing.JPanel();
        lblprefTime = new javax.swing.JLabel();
        txtFieldprelTime = new javax.swing.JTextField();
        lblPrefhours = new javax.swing.JLabel();
        lblTimeTaken = new javax.swing.JLabel();
        txtFieldTimeTaken = new javax.swing.JTextField();
        lblTakenHours = new javax.swing.JLabel();
        panelSolution1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        txtsolution1 = new javax.swing.JTextArea();
        panelSaveAndClose = new javax.swing.JPanel();
        btnSaveCase = new javax.swing.JButton();
        btnCloseCaseWindow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCases = new javax.swing.JList();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        btnSearchCat = new javax.swing.JButton();
        btnSearchID = new javax.swing.JButton();
        btnSearchAssigne = new javax.swing.JButton();
        btnCreateCase = new javax.swing.JButton();
        btnSearchStatus = new javax.swing.JButton();
        btnOpenCase = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        btnReftresh = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbleCases = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        panelCaseProperties.setBackground(new java.awt.Color(219, 219, 219));
        panelCaseProperties.setBorder(javax.swing.BorderFactory.createTitledBorder("Case Properties"));

        lblCaseId.setText("CaseID:");

        txtCaseIdNr.setEditable(false);
        txtCaseIdNr.setBackground(new java.awt.Color(153, 153, 153));
        txtCaseIdNr.setText("case0000322");
        txtCaseIdNr.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtCaseIdNrActionPerformed(evt);
            }
        });

        lblCategory.setText("Category:");

        comboCategory.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Network" }));
        comboCategory.addItemListener(new java.awt.event.ItemListener()
        {
            public void itemStateChanged(java.awt.event.ItemEvent evt)
            {
                comboCategoryItemStateChanged(evt);
            }
        });

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assigned" }));

        lblStatus.setText("Status:");

        lblAssignedTo.setText("Assigned to:");

        comboAssigned.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Not Assigned" }));

        lblCreated.setText("Created:");

        txtCreateDate.setEditable(false);
        txtCreateDate.setBackground(new java.awt.Color(153, 153, 153));
        txtCreateDate.setText("2015-05-03; 13:58");

        lblChanged.setText("Changed:");

        txtTimeChanged.setEditable(false);
        txtTimeChanged.setBackground(new java.awt.Color(153, 153, 153));
        txtTimeChanged.setText("2015-05-04; 09:23");
        txtTimeChanged.setRequestFocusEnabled(false);

        panelRequesterInfo.setBackground(new java.awt.Color(219, 219, 219));
        panelRequesterInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Requester Information"));

        lblUsername.setText("Username:");
        lblUsername.setToolTipText("");

        lblName.setText("Full Name:");
        lblName.setToolTipText("");

        lblPhone.setText("Phone:");

        txtUserName.setText("katgus");

        txtFullName.setText("Katarina Gustavsson");

        txtphone.setText("+46712345678");

        lblDepartment.setText("Department:");

        lblCity.setText("City:");

        lblComputerName.setText("Computername:");

        txtComputerName.setText("klom-t3424");

        comboBoxCity.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Berlin" }));

        txtFieldAvd.setText("Finance");

        javax.swing.GroupLayout panelRequesterInfoLayout = new javax.swing.GroupLayout(panelRequesterInfo);
        panelRequesterInfo.setLayout(panelRequesterInfoLayout);
        panelRequesterInfoLayout.setHorizontalGroup(
            panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRequesterInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRequesterInfoLayout.createSequentialGroup()
                        .addComponent(lblUsername)
                        .addGap(18, 18, 18)
                        .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelRequesterInfoLayout.createSequentialGroup()
                        .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblName)
                            .addComponent(lblPhone))
                        .addGap(18, 18, 18)
                        .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFullName, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                            .addComponent(txtphone))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRequesterInfoLayout.createSequentialGroup()
                        .addComponent(lblComputerName)
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRequesterInfoLayout.createSequentialGroup()
                        .addComponent(lblCity)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRequesterInfoLayout.createSequentialGroup()
                        .addComponent(lblDepartment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldAvd)
                    .addComponent(comboBoxCity, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtComputerName, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelRequesterInfoLayout.setVerticalGroup(
            panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRequesterInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDepartment)
                    .addComponent(txtFieldAvd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtFullName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCity)
                    .addComponent(comboBoxCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelRequesterInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblComputerName)
                    .addComponent(txtComputerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        lblCreatedBy.setText("Created By:");

        txtFieldCreatedBy.setEditable(false);
        txtFieldCreatedBy.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldCreatedBy.setText("jTextField4");

        javax.swing.GroupLayout panelCasePropertiesLayout = new javax.swing.GroupLayout(panelCaseProperties);
        panelCaseProperties.setLayout(panelCasePropertiesLayout);
        panelCasePropertiesLayout.setHorizontalGroup(
            panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblCaseId)
                .addGap(18, 18, 18)
                .addComponent(txtCaseIdNr, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lblCreated)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblChanged)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTimeChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCasePropertiesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panelRequesterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(238, 238, 238))
                    .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                        .addComponent(lblCategory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                        .addComponent(lblAssignedTo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                        .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblStatus)
                            .addComponent(lblCreatedBy))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFieldCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        panelCasePropertiesLayout.setVerticalGroup(
            panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCasePropertiesLayout.createSequentialGroup()
                .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCaseIdNr, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCaseId)
                        .addComponent(lblCreated)
                        .addComponent(txtCreateDate, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblChanged)
                        .addComponent(txtTimeChanged, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStatus)
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategory)
                    .addComponent(comboCategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreatedBy)
                    .addComponent(txtFieldCreatedBy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCasePropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboAssigned, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAssignedTo))
                    .addComponent(panelRequesterInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelCaseRequest.setBackground(new java.awt.Color(219, 219, 219));
        panelCaseRequest.setBorder(javax.swing.BorderFactory.createTitledBorder("Case Description"));

        txtTitle.setText("Can't connect to www.ltu.se");

        lblTitle1.setText("Title:");

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        txtDescription.setText("I can't connect to http://www.ltu.se no matter what I do. \nI have been trying all day long");
        jScrollPane3.setViewportView(txtDescription);

        javax.swing.GroupLayout panelCaseRequestLayout = new javax.swing.GroupLayout(panelCaseRequest);
        panelCaseRequest.setLayout(panelCaseRequestLayout);
        panelCaseRequestLayout.setHorizontalGroup(
            panelCaseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaseRequestLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCaseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                    .addGroup(panelCaseRequestLayout.createSequentialGroup()
                        .addComponent(lblTitle1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitle)))
                .addContainerGap())
        );
        panelCaseRequestLayout.setVerticalGroup(
            panelCaseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaseRequestLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(panelCaseRequestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle1)
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelWorkTask.setBackground(new java.awt.Color(219, 219, 219));
        panelWorkTask.setBorder(javax.swing.BorderFactory.createTitledBorder("Worktask"));

        listWorkTask.setBackground(new java.awt.Color(153, 153, 153));
        listWorkTask.setModel(new javax.swing.AbstractListModel()
        {
            String[] strings = { "1. Ask if his collegues have the same issues", "2. Verify if local resources is accisable", "2. Ask user to thest with network cable plugged in", "3. Ask user to restart the computer", "If above doesn't work:", "1. Connect to switch and verify uptime" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listWorkTask);

        javax.swing.GroupLayout panelWorkTaskLayout = new javax.swing.GroupLayout(panelWorkTask);
        panelWorkTask.setLayout(panelWorkTaskLayout);
        panelWorkTaskLayout.setHorizontalGroup(
            panelWorkTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWorkTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelWorkTaskLayout.setVerticalGroup(
            panelWorkTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWorkTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelComments.setBorder(javax.swing.BorderFactory.createTitledBorder("Comments"));

        txtComments.setColumns(20);
        txtComments.setRows(5);
        txtComments.setText("Enter some comments here\n");
        jScrollPane4.setViewportView(txtComments);

        jButton1.setText("Read Comments");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelCommentsLayout = new javax.swing.GroupLayout(panelComments);
        panelComments.setLayout(panelCommentsLayout);
        panelCommentsLayout.setHorizontalGroup(
            panelCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCommentsLayout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelCommentsLayout.setVerticalGroup(
            panelCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCommentsLayout.createSequentialGroup()
                .addGroup(panelCommentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelCommentsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTimeInfo.setBackground(new java.awt.Color(219, 219, 219));
        panelTimeInfo.setBorder(javax.swing.BorderFactory.createTitledBorder("Time information"));
        panelTimeInfo.setPreferredSize(new java.awt.Dimension(425, 140));
        panelTimeInfo.setRequestFocusEnabled(false);

        lblprefTime.setText("Prefer time taken:");

        txtFieldprelTime.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtFieldprelTime.setText("3");

        lblPrefhours.setText("hours");

        lblTimeTaken.setText("Time taken:");

        txtFieldTimeTaken.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtFieldTimeTaken.setText(" Enter total time when closed");

        lblTakenHours.setText("hours");

        javax.swing.GroupLayout panelTimeInfoLayout = new javax.swing.GroupLayout(panelTimeInfo);
        panelTimeInfo.setLayout(panelTimeInfoLayout);
        panelTimeInfoLayout.setHorizontalGroup(
            panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimeInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblprefTime)
                    .addComponent(lblTimeTaken))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldprelTime, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(txtFieldTimeTaken, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrefhours)
                    .addComponent(lblTakenHours))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelTimeInfoLayout.setVerticalGroup(
            panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTimeInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprefTime)
                    .addComponent(txtFieldprelTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPrefhours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelTimeInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldTimeTaken, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimeTaken)
                    .addComponent(lblTakenHours)))
        );

        panelSolution1.setBackground(new java.awt.Color(219, 219, 219));
        panelSolution1.setBorder(javax.swing.BorderFactory.createTitledBorder("Solution"));

        txtsolution1.setColumns(20);
        txtsolution1.setRows(5);
        txtsolution1.setText("Enter your solution here...");
        jScrollPane6.setViewportView(txtsolution1);

        javax.swing.GroupLayout panelSolution1Layout = new javax.swing.GroupLayout(panelSolution1);
        panelSolution1.setLayout(panelSolution1Layout);
        panelSolution1Layout.setHorizontalGroup(
            panelSolution1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSolution1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelSolution1Layout.setVerticalGroup(
            panelSolution1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSolution1Layout.createSequentialGroup()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panelSaveAndClose.setBackground(new java.awt.Color(219, 219, 219));
        panelSaveAndClose.setBorder(javax.swing.BorderFactory.createTitledBorder("Save and Close"));

        btnSaveCase.setText("Save Case");
        btnSaveCase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnSaveCaseActionPerformed(evt);
            }
        });

        btnCloseCaseWindow.setText("Cancel");
        btnCloseCaseWindow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCloseCaseWindowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSaveAndCloseLayout = new javax.swing.GroupLayout(panelSaveAndClose);
        panelSaveAndClose.setLayout(panelSaveAndCloseLayout);
        panelSaveAndCloseLayout.setHorizontalGroup(
            panelSaveAndCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaveAndCloseLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnSaveCase, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCloseCaseWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        panelSaveAndCloseLayout.setVerticalGroup(
            panelSaveAndCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSaveAndCloseLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(panelSaveAndCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCloseCaseWindow)
                    .addComponent(btnSaveCase)))
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCaseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(panelComments, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelSolution1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelWorkTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTimeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(panelSaveAndClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelCaseProperties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(298, 298, 298)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(panelWorkTask, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelTimeInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelSaveAndClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(5, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addComponent(panelCaseRequest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelSolution1, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(panelComments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDialog1Layout.createSequentialGroup()
                    .addGap(2, 2, 2)
                    .addComponent(panelCaseProperties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(599, Short.MAX_VALUE)))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Open cases"));
        jScrollPane1.setViewportView(listCases);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remember Case Software");
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowClosing(java.awt.event.WindowEvent evt)
            {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(219, 219, 219));

        lblTitle.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 36)); // NOI18N
        lblTitle.setText("Remember Case Software");

        btnSearchCat.setText("Search by Category");

        btnSearchID.setText("Search by CaseID");

        btnSearchAssigne.setText("Search By Assigne");

        btnCreateCase.setText("New Case");
        btnCreateCase.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnCreateCaseActionPerformed(evt);
            }
        });

        btnSearchStatus.setText("Search by Status");

        btnOpenCase.setText("Open Case");

        btnReports.setText("Reports");

        btnReftresh.setText("jButton2");
        btnReftresh.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnReftreshActionPerformed(evt);
            }
        });

        jScrollPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Open Cases"));

        tbleCases.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String []
            {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tbleCases);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnSearchStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchCat, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearchAssigne)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnReports)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnReftresh)
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCreateCase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnOpenCase, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(btnOpenCase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCreateCase))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnReftresh)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearchCat)
                    .addComponent(btnSearchID)
                    .addComponent(btnSearchAssigne)
                    .addComponent(btnSearchStatus)
                    .addComponent(btnReports))
                .addGap(26, 26, 26))
        );

        jMenu1.setText("File");

        jMenuItem1.setText("Connect to database");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Exit");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Help");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateCaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCreateCaseActionPerformed
    {//GEN-HEADEREND:event_btnCreateCaseActionPerformed
        callNewCaseDialog();
        
        
        
    }//GEN-LAST:event_btnCreateCaseActionPerformed

    private void callNewCaseDialog()
    {
        NewJDialog dia = new NewJDialog(this, rootPaneCheckingEnabled);
        
        dia.setVisible(true);
        updateList();
        
        
    }
    
    private void updateList()
    {
        
        DefaultListModel m = new DefaultListModel();
        
        Connection conn = null;
        ResultSet rs = null;
        PreparedStatement pst = null;
        String DBURL = "jdbc:derby://localhost:1527/AES;user=wallejr;password=aik71111";
        
        
        
        try
        {
            Class.forName("org.apache.derby.jdbc.ClientDriver");
            conn = DriverManager.getConnection(DBURL);
            
            String sql = "select * from WALLEJR.CASES";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            tbleCases.setModel(DbUtils.resultSetToTableModel(rs));
            
            
//            while (rs.next()) 
//            {
//                int caseID = rs.getInt("CASEID");
//                String titel = rs.getString("TITEL");
//                m.addElement(caseID);
//                m.addElement(titel);
//            }
//            listCases.setModel(m);
            conn.close();
            

        }
        catch(SQLException e)
        {
            System.err.println("SQLException: " + e.getMessage());
        }
        catch(ClassNotFoundException clExc)
        {
            
        }
    }
    
    private void formWindowClosing(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosing
    {//GEN-HEADEREND:event_formWindowClosing
      
    }//GEN-LAST:event_formWindowClosing

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void txtCaseIdNrActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtCaseIdNrActionPerformed
    {//GEN-HEADEREND:event_txtCaseIdNrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCaseIdNrActionPerformed

    private void comboCategoryItemStateChanged(java.awt.event.ItemEvent evt)//GEN-FIRST:event_comboCategoryItemStateChanged
    {//GEN-HEADEREND:event_comboCategoryItemStateChanged
        String selected = comboCategory.getSelectedItem().toString();

        switch(selected)
        {
            case "Network":
            comboAssigned.setModel(new DefaultComboBoxModel<>(PersonalNetwork.values()));
            break;
            case "Security":
            comboAssigned.setModel(new DefaultComboBoxModel<>(PersonalSecurity.values()));
            break;
            case "Installation":
            comboAssigned.setModel(new DefaultComboBoxModel<>(PersonalInstallation.values()));
            break;
            case "Users":
            comboAssigned.setModel(new DefaultComboBoxModel<>(PersonalUsers.values()));
            break;
        } //End
    }//GEN-LAST:event_comboCategoryItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveCaseActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnSaveCaseActionPerformed
    {//GEN-HEADEREND:event_btnSaveCaseActionPerformed
        //saveCase();
    }//GEN-LAST:event_btnSaveCaseActionPerformed

    private void btnCloseCaseWindowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnCloseCaseWindowActionPerformed
    {//GEN-HEADEREND:event_btnCloseCaseWindowActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCloseCaseWindowActionPerformed

    private void btnReftreshActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnReftreshActionPerformed
    {//GEN-HEADEREND:event_btnReftreshActionPerformed
            updateList();// TODO add your handling code here:
    }//GEN-LAST:event_btnReftreshActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new startForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseCaseWindow;
    private javax.swing.JButton btnCreateCase;
    private javax.swing.JButton btnOpenCase;
    private javax.swing.JButton btnReftresh;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSaveCase;
    private javax.swing.JButton btnSearchAssigne;
    private javax.swing.JButton btnSearchCat;
    private javax.swing.JButton btnSearchID;
    private javax.swing.JButton btnSearchStatus;
    private javax.swing.JComboBox comboAssigned;
    private javax.swing.JComboBox comboBoxCity;
    private javax.swing.JComboBox comboCategory;
    private javax.swing.JComboBox comboStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lblAssignedTo;
    private javax.swing.JLabel lblCaseId;
    private javax.swing.JLabel lblCategory;
    private javax.swing.JLabel lblChanged;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblComputerName;
    private javax.swing.JLabel lblCreated;
    private javax.swing.JLabel lblCreatedBy;
    private javax.swing.JLabel lblDepartment;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPrefhours;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTakenHours;
    private javax.swing.JLabel lblTimeTaken;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JLabel lblprefTime;
    private javax.swing.JList listCases;
    private javax.swing.JList listWorkTask;
    private javax.swing.JPanel panelCaseProperties;
    private javax.swing.JPanel panelCaseRequest;
    private javax.swing.JPanel panelComments;
    private javax.swing.JPanel panelRequesterInfo;
    private javax.swing.JPanel panelSaveAndClose;
    private javax.swing.JPanel panelSolution1;
    private javax.swing.JPanel panelTimeInfo;
    private javax.swing.JPanel panelWorkTask;
    private javax.swing.JTable tbleCases;
    private javax.swing.JTextField txtCaseIdNr;
    private javax.swing.JTextArea txtComments;
    private javax.swing.JTextField txtComputerName;
    private javax.swing.JTextField txtCreateDate;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtFieldAvd;
    private javax.swing.JTextField txtFieldCreatedBy;
    private javax.swing.JTextField txtFieldTimeTaken;
    private javax.swing.JTextField txtFieldprelTime;
    private javax.swing.JTextField txtFullName;
    private javax.swing.JTextField txtTimeChanged;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtUserName;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextArea txtsolution1;
    // End of variables declaration//GEN-END:variables
}
